"""Auto migration

Revision ID: 06360969ed1a
Revises: fa0309a508a5
Create Date: 2025-04-09 01:50:46.386733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06360969ed1a'
down_revision = 'fa0309a508a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customization_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('skin', 'shirt', 'shoes', name='customization_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('item_cost', sa.Integer(), nullable=False),
    sa.Column('model_key', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avatar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_name', sa.String(length=20), nullable=False),
    sa.Column('avatar_energy', sa.Integer(), nullable=False),
    sa.Column('skin_id', sa.Integer(), nullable=True),
    sa.Column('shirt_id', sa.Integer(), nullable=True),
    sa.Column('shoes_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('avatar_energy >= 0 AND avatar_energy <= 100', name='check_avatar_energy_range'),
    sa.ForeignKeyConstraint(['shirt_id'], ['customization_items.id'], ),
    sa.ForeignKeyConstraint(['shoes_id'], ['customization_items.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['customization_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avatar')
    op.drop_table('customization_items')
    # ### end Alembic commands ###
